# Generated by Django 5.1.4 on 2025-01-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1, max_length=50, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
