# Generated by Django 5.1.4 on 2025-02-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=1, upload_to='product_photo', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
