# Generated by Django 5.1.4 on 2025-01-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about_photo/')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year_in_buisness', models.IntegerField(verbose_name='Лет в бизнесе')),
                ('happy_people', models.IntegerField(verbose_name='Довольных клиентов')),
                ('sales', models.IntegerField(verbose_name='Продаж')),
                ('award_winning', models.IntegerField(verbose_name='Наград')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
