# Generated by Django 5.1.4 on 2025-02-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_team_facebook_alter_team_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='blog_photo/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикаций')),
            ],
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новость'},
        ),
    ]
