# Generated by Django 5.1.4 on 2025-02-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blog_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Сотрудника', 'verbose_name_plural': 'Команда'},
        ),
    ]
