# Generated by Django 5.1.4 on 2025-03-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Поддержка',
            },
        ),
    ]
