# Generated by Django 5.1.4 on 2025-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contactsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsupport',
            name='coordinates',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactsupport',
            name='email_info',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactsupport',
            name='email_support',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactsupport',
            name='hot_line',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
